---
abstract: 'File finder based on Path::Iterator::Rule, but using IO::All'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  File::pushd: 0
  Path::Class: 0
  Test::Deep: 0
  Test::More: 0.92
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-All-Rule
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  IO::All::Rule:
    file: lib/IO/All/Rule.pm
    version: 0.001
requires:
  IO::All: 0
  IO::Dir: 0
  Path::Iterator::Rule: 0
  namespace::clean: 0
  parent: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/io-all-rule/issues
  homepage: https://metacpan.org/release/IO-All-Rule
  repository: git://github.com/dagolden/io-all-rule.git
version: 0.001
